version: '3.8'

services:
  vectordb:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src
      - COHERE_API_KEY=${COHERE_API_KEY:-your_cohere_api_key_here}
    volumes:
      # Persist data across container restarts
      - vectordb_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - vectordb_network

  # Optional: Add a simple nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vectordb
    networks:
      - vectordb_network
    profiles:
      - production

volumes:
  vectordb_data:
    driver: local

networks:
  vectordb_network:
    driver: bridge